export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA';
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT';

export const SEARCH_PROJECT_SAGA = 'SEARCH_PROJECT_SAGA';

export const ADD_USER_PROJECT_API = 'ADD_USER_PROJECT_API';
export const REMOVE_USER_PROJECT_API = 'REMOVE_USER_PROJECT_API';

export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';
export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL';
export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';

export const EDIT_PROJECT = 'EDIT_PROJECT';

