export const USER_SIGNIN_API = 'USER_SIGNIN_API';

/**
 * Login
 */

export const USLOGIN = 'USLOGIN'

export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA';
export const GET_USER_BY_PROJECT_ID = 'GET_USER_BY_PROJECT_ID';